version: '3.4'
services:
  psql: 
    image: postgres
    environment:
      POSTGRES_USER: alex01
      POSTGRES_PASSWORD: pwd1234
    ports:
      - "54321:5432"
    volumes:
      - type: volume
        source: mydata
        target: /mydata
volumes:
  mydata: 
    name: "mydata"